# Generated by Django 4.2.4 on 2024-02-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("vorname", models.CharField(max_length=100, verbose_name="Vorname")),
                ("nachname", models.CharField(max_length=100, verbose_name="Nachname")),
                ("klasse", models.CharField(max_length=3, verbose_name="Klasse")),
                ("ankunft", models.DateTimeField(default=0, verbose_name="Ankunft")),
                ("qr_id", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Anwesenheitsliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ankunft", models.DateTimeField(verbose_name="Ankunft")),
                ("verlassen", models.DateTimeField(verbose_name="Verlassen")),
                (
                    "aufenthaltsdauer",
                    models.FloatField(verbose_name="Aufenthaltsdauer"),
                ),
                (
                    "kommentar",
                    models.CharField(max_length=100, verbose_name="Kommentar"),
                ),
                (
                    "qr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.person"
                    ),
                ),
            ],
        ),
    ]
