# Generated by Django 5.1.2 on 2024-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="ankunft",
            field=models.DateTimeField(default=0, null=True, verbose_name="Ankunft"),
        ),
    ]
