# Generated by Django 4.2.4 on 2023-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_aufzeichnungen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aufzeichnungen",
            name="ankunft",
            field=models.DateTimeField(verbose_name="Ankunft"),
        ),
        migrations.AlterField(
            model_name="aufzeichnungen",
            name="verlassen",
            field=models.DateTimeField(verbose_name="Verlassen"),
        ),
    ]
