# Generated by Django 4.2.4 on 2023-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_aufzeichnungen_ankunft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aufzeichnungen",
            name="kommentar",
            field=models.CharField(max_length=100, verbose_name="Kommentar"),
        ),
    ]
