# Generated by Django 4.2.4 on 2023-10-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_remove_anwesenheitsliste_qr_id_anwesenheitsliste_qr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="ankunft",
            field=models.DateTimeField(default=0, verbose_name="Ankunft"),
        ),
    ]
