# Generated by Django 4.2.4 on 2023-11-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_person_ankunft"),
    ]

    operations = [
        migrations.AddField(
            model_name="anwesenheitsliste",
            name="aufenthaltsdauer",
            field=models.FloatField(default=0, verbose_name="Aufenthaltsdauer"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person", name="qr_id", field=models.IntegerField(default=1),
        ),
    ]
